version: '3'

services:
  node:
    build:
      context: ./dockerfiles/nodejs/
      dockerfile: Dockerfile
    image: fanneioz/sandbox/nodejs:latest    
    environment:
      - NODE_ENV=development
    volumes:
      - .:/vagrant
  postgres:
    build:
      context: ./dockerfiles/postgresql/
      dockerfile: Dockerfile
    image: fanneioz/sandbox/postgres:latest
    links:
      - node
    environment:
      POSTGRES_PASSWORD: backend
      POSTGRES_USER: backend
      POSTGRES_DB: backend
  mongo:
    image: mongo:bionic
    environment:
      # TODO: Solve authentication error from adminer > mongo
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'example'    
    links:
      - node
  redis:
    image: redis:alpine3.11
    links:
      - node
  adminer:
    build:
      context: ./dockerfiles/adminer/
      dockerfile: Dockerfile
    image: fanneioz/sandbox/adminer:latest
    links:
      - postgres
      - mongo    
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: postgres
  nginx:
    build:
      context: ./dockerfiles/nginx/
      dockerfile: Dockerfile
    image: fanneioz/sandbox/nginx:latest
    links:
      - node
      - adminer
    ports: 
      - 80:80
    volumes:
      - .:/var/www/root
