version: '3'

services:
    node:
        build:
            context: ./dockerfiles/nodejs/
            dockerfile: Dockerfile
        image: fanneioz/sandbox/nodejs:latest
        ports: 
            - 3000:3000
            - 30080:80
            - 38080:8080
        environment: 
            - NODE_ENV=development
        volumes: 
            - .:/vagrant
    postgres:
        build:
            context: ./dockerfiles/postgresql/
            dockerfile: Dockerfile
        image: fanneioz/sandbox/postgres:latest
        links:
            - node            
    
            