version: '3'

services:
    node:
        build:
            context: ./dockerfiles/nodejs/
            dockerfile: Dockerfile
        image: tman/sandbox/nodejs:latest
        container_name: nodejs
        ports: 
            - 3000:3000
           # - 30080:80
           # - 38080:8080
        environment: 
            - NODE_ENV=development
        volumes: 
            - .:/finalend
    postgres:
        build:
            context: ./dockerfiles/postgresql/
            dockerfile: Dockerfile
        image: tman/sandbox/postgres:latest
        container_name: postgres
        links:
            - node            
    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro 
            