version: '3'

services:
    node:
        build:
            context: ./dockerfiles/nodejs/
            dockerfile: Dockerfile
        image: tman/sandbox/nodejs:latest
        container_name: nodejs
        ports: 
            - 3000:3000
            - 30080:80
            - 38080:8080
        environment: 
            - NODE_ENV=development
        volumes: 
            - .:/finalend
    postgres:
        build:
            context: ./dockerfiles/postgresql/
            dockerfile: Dockerfile
        image: tman/sandbox/postgres:latest
        links:
            - node            
    
            