version: '3'

services:
    # build-env:
    #     build:
    #         context: ./dockerfiles/development/
    #         dockerfile: Dockerfile
    #     image: fanneioz/sandbox/development:latest
    #     volumes: 
    #         - .:/vagrant
    node:
        build:
            context: ./dockerfiles/nodejs/
            dockerfile: Dockerfile
        image: fanneioz/sandbox/nodejs:latest
        ports: 
            - 3000:3000
            - 30080:80
            - 38080:8080
        environment: 
            - NODE_ENV=development
        volumes:
            - .:/vagrant
