version: '3'

services:
    # build-env:
    #     build:
    #         context: ./dockerfiles/development/
    #         dockerfile: Dockerfile
    #     image: fanneioz/sandbox/development:latest
    #     volumes: 
    #         - .:/vagrant
    node:
        build:
            context: ./dockerfiles/nodejs/
            dockerfile: Dockerfile
        image: fanneioz/sandbox/nodejs:latest
        ports: 
            - 3000:3000
            - 30080:80
            - 38080:8080
        environment: 
            - NODE_ENV=development
        volumes: 
            - .:/vagrant
    postgres:
        build:
            context: ./dockerfiles/postgresql/
            dockerfile: Dockerfile
        image: fanneioz/sandbox/postgres:latest
        ports:
            - 5432:5432
        environment: 
            # TODO: Fix POSTGRES_PASSWORD not work properly
            POSTGRES_PASSWORD: P@$$w0rd            
            POSTGRES_USER: backend
            POSTGRES_DB: backend
    mongo:
        image: mongo:bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example